### PR TITLE
support for associating public ip

### PR DESCRIPTION
**Pull request by sermilrod**
This MR aims to provide support for automatic public ip allocation

### CODE REVIEW

**Comment by pdion891** [comment]
That's a nice feature, does it support VPC ?

**Comment by sermilrod** [comment]
@pdion891 yes it does. Public IP belongs to the VPC and the way this new feature works is by setting the port forwarding rule that allows you to have direct connectivity with the VM

**Comment by fifthecho** [comment]
Sorry for my slow response here. I'm merging this now and will update RubyGems tomorrow.

**Comment by fifthecho** [comment]
Pushed.

**Pull request merged**
