### PR TITLE
Hostname setting

### PR DESCRIPTION
**Pull request by jeffersongirao**
Chef does not play well with long hostname since it generates some temp files based on it and it causes an exception ENAMETOOLONG, allowing for setting the hostname is useful in the case your cloudstack implementation is generating long hostnames.

### CODE REVIEW

**Comment by jeffersongirao** [comment]
Hello @fifthecho! Any feedback on this? Thanks!

**Comment by fifthecho** [comment]
Sorry for the late reply. Merging now. Will bundle and push the new gem soon.

**Comment by jeffersongirao** [comment]
@fifthecho Thanks!

**Comment by fifthecho** [comment]
This has been pushed to RubyGems. Thanks for the patience.

**Pull request merged**
